; Package name
NAME    = goserver
; Package version
VERSION = v1

[env]
environment = "dev"
initRobotInfo = OFF
initRobotHead = ON
adjustReport = OFF
location = "Asia/Kolkata"

[ng]
devApiUrl = "https://gw.factory.ng99.xyz"
procApiUrl = "https://gw.k1games.fun"
accessKey = "8KFEGF8BC3AKVCI2"
proxyUrl = "http://13.229.184.158:3128"
headUrl= "https://cdn.g2qdh.com/head"

[nsq]
addr = "127.0.0.1:4150"

[nats]
url = "nats://@127.0.0.1:4222"

[redis]
addr = "127.0.0.1:6379"

[mysqld]
host   = "127.0.0.1"
port   = "3306"
user   = "root"
passwd = "root"
name   = "test"
prefix = "t_"

[mongod]
host   = "127.0.0.1"
port   = "27017"
user   =
passwd =
name   = "test"
prefix = "c_"

[mongod.log]
host   = "127.0.0.1"
port   = "27019"
user   =
passwd =
name   = "test"
prefix = "c_"

[clickhouse]
# dsn = "clickhouse://user:password@192.168.0.137:9000/game?dial_timeout=10s&read_timeout=20s"
addr = "172.31.1.81:9000"
database = "game"
username = ""
password = ""
dial_timeout = 10 # second
read_timeout = 20 # second
logsql = OFF

[kafka]
enable = ON
addr = "172.31.1.81:9092"

[mongod.gate]

[gate]
; aes encrypt status
status = OFF
; aes encrypt key
key  = "ihyNwXfVlCiIu9Oydd4l2kuzf3i7WXg8uuwU5iysj0o"
; session secret
secret  = "XKycdHdDGPje3Ns7rJ0FjVeaDREuo6TW8Ub61Zuuqo8"
; tourist login aes decrypt key
tourist = "cdHdDGPje3Ns7rJ0"

; gate.node(id)
[gate.node1]
; grpc addr
bind = "127.0.0.1:8004"
; node kind
kind = "8qYBRmwKEk/WjfFYdbN4idnqsW0phsrkcvMcYA6jtCE"
; websocket addr
addr = "0.0.0.0:4107"
addr2 = "0.0.0.0:4108"
; test
host = "127.0.0.1:4107"
host2 = "127.0.0.1:4108"

[login]
; grpc addr
bind = "127.0.0.1:8001"
; node kind
kind = "GlwSmb2PIBDf3buIe0D267naQBi2HDkgd3Ytxy4MR0E"
; login addr
; addr = "127.0.0.1:8002"
addr = "0.0.0.0:8002"
; aes encrypt status
status = OFF
; aes encrypt key
key  = "ihyNwXfVlCiIu9Oydd4l2kuzf3i7WXg8uuwU5iysj0o"

[dbms]
; grpc addr
bind = "127.0.0.1:7001"
; node name
kind = "aMJ28IguIbnYIGhwfb1eBG40lJC0klmGNw+OQPkw2R8"
; room kind
room = "srtWp/eR7Qc7/BXh+N+34no7a3gWGD2bE8XYMJtua44"
; role kind
role = "LjUeuk9naK9tk6k+xhia5FSXBcxfKlpcc7nlMVGQkv4"
; logger kind
logger = "A0IUe/DK5Hd/vQQ2bG3tiZaft11EYXeX+7moz94ixbo"
; report kind
report = "8IegemL1x3exhsSS4jHvDxKrUlMyC50b7n^vEVOkE0U"

[sms]
; grpc addr
bind = "127.0.0.1:8010"
; node kind
kind = "U2FsdGVkX1+/6l99TN9RfQzYmRNzVfdMPh1SXaHK1SU="
; login addr
; addr = "127.0.0.1:8002"
addr = "0.0.0.0:8012"
; aes encrypt status
status = OFF
; aes encrypt key
key  = "ihyNwXfVlCiIu9Oydd4l2kuzf3i7WXg8uuwU5iysj0o"

[sms-service]
addr = "127.0.0.1:8012"

[robot]
; grpc addr
bind = "127.0.0.1:7003"
; node kind
kind = "gF7qwESVkfAfJDNn5W5jPrbjIIyeKo6aW4CkZAECKW8"
;
phone = "13788888888"
;
passwd = "your-password"

[game]

;game.{serv}{servid}
[game.hua1]
; grpc addr
bind    = "127.0.0.1:9021"
; node kind
kind = "w+5AmRbGYtoVmHIW16QDRDcSqwFVWRIW8kh2EWubmhQ"
; card
; card1 = "11,12,13"
; card2 = "14,15,16"
; card3 = "17,18,19"

;game.{serv}{servid}
[game.hua_21]
; grpc addr
bind    = "127.0.0.1:9031"
; node kind
kind = "w+U2FsdGVkX18PDLPM32breCiEz0Vdw49C3Z48FoDHU7V9ks4fNEkRvLunk/YNeA1i"

;game.{serv}{servid}
[game.joker1]
; grpc addr
bind    = "127.0.0.1:9121"
; node kind
kind = "d7a5GxGDSsqeHwadFcwy0KI5FGqlQfXIq6NhdaXrTED"
; card
; card1 = "11,12"

;game.{serv}{servid}
[game.ak471]
; grpc addr
bind    = "127.0.0.1:9221"
; node kind
kind = "0ms550WgS5iZ0vlzVlJl9G2j8tQPXU8ys5hqPTQdIai"

;game.{serv}{servid}
[game.rummy1]
; grpc addr
bind    = "127.0.0.1:9001"
; node kind
kind = "4r8UFgVWkYEeElI92bqQIcMkDF/6doliKgWID7qgEQ8"

;game.{serv}{servid}
[game.rummy_21]
; grpc addr
bind    = "127.0.0.1:9011"
; node kind
kind = "U2FsdGVkX18gUxioyu6ImBe7QU10TemnXJmNOlXkTm0="

;game.{serv}{servid}
[game.lhd1]
; grpc addr
bind    = "127.0.0.1:9041"
; node kind
kind = "kIR7JhAmKfWlnCgv1ZymXGkYKbDgeaTJT/jZBBmxpTI"

;game.{serv}{servid}
[game.7up1]
; grpc addr
bind    = "127.0.0.1:9141"
; node kind
kind = "U2FsdGVkX1/A6iCtI8oeeR7thB6X+sACri12hNb8AeU="

;game.{serv}{servid}
[game.crash1]
; grpc addr
bind    = "127.0.0.1:9241"
; node kind
kind = "U2FsdGVkX19GhlQ2tKRNee+rlel1qcFTx5xgW/OXJng="
boom = ""

;game.{serv}{servid}
[game.andarbahar1]
; grpc addr
bind    = "127.0.0.1:9341"
; node kind
kind = "U2FsdGVkX19jWeO6c0AdqBBeW9iNHmzmWjSvasWAM7E="

;game.{serv}{servid}
[game.lottery1]
; grpc addr
bind    = "127.0.0.1:9441"
; node kind
kind = "U2FsdGVkX1/qIipfOikVYmP5VbPtoQS4aCudxPm4Bow="

;game.{serv}{servid}
[game.plane1]
; grpc addr
bind    = "127.0.0.1:9451"
; node kind
kind = "U2FsdGVkX19wu1v7B4wolca+BNCqTJ4n/M9XY4PKAHE="

;game.{serv}{servid}
[game.rb1]
; grpc addr
bind    = "127.0.0.1:9551"
; node kind
kind = "U2FsdGVkX1+eMo8NEMwQ/qshTPgAOrwQP+SlYo3RvXA="
winner = "1"
luck   = "3"

[game.mines1]
bind    = "127.0.0.1:9651"
kind = "MTI3LjAuMC4xOjk2NTE="

[activity.betrank]
bind    = "127.0.0.1:9901"
kind = "MTI3LjAuMC4xOjk5MDE="

[tool]

[weixin]
notifyPattern = "/happy/wxpay/notice"
notifyUrl     = "https://xxx.com/happy/wxpay/notice"
appid         = "wx999999999999999c"
appsecret     = "88888888888888888888888888888888"
appkey        = "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF"
mchid         = "1111111111"

[wxmp]
pattern       = "/wxmp/wx"
appid         = "wx999999999999999c"
appsecret     = "88888888888888888888888888888888"
serverURL     = "https://xxx.com/wxmp/wx"
; 2-32 char
token         = "IpBvKRKlvf5b2h/I6RRIxLJ0b4uoX9fK"
; 43 char
encoding-AES-key = "0ngO6hjyKhhpEoSSzvyEQ3Yqu1UD0qfDGdnvm9Q3w7c"
; redirect_uri
redirect_uri  = "https://xxx.com/happy/wxmp/oauth2"
; scope (snsapi_userinfo, snsapi_base)
scope = "snsapi_userinfo"

[smsbao]
status = OFF
username = "11111111111"
password = "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"

[sms253]
status = OFF
account = "CN1111111"
password = "xxxxxxxxxxxxxx"
url = "http://smssh1.253.com/msg/send/json"

[smsbk]
status = OFF
appid = "U68zCsVP"
account = "PVxIvla0"
password = "24qPE8ci"
url = "https://api.onbuka.com/v3/sendSms"

[smskmi]
status = ON
accessKey = "e9fce16d048b4225bdd676b649309f59"
secretKey = "e391cecb906941da983ab2595be59394"
url = "http://api.kmicloud.com/sms/send/v1/otp"

[smsmt]
status = ON
appkey = "1X7wAD"
appsecret = "jh2CDi"
appcode = "1000"
url = "http://43.133.60.95:9090/sms/batch/v2"

[smsxxy]
status = ON
appkey = "acQ3fF"
appsecret = "PaaQr1"
appcode = "1000"
url = "http://190.92.241.159:9090/sms/batch/v2"

[smscl]
status = ON
apiaccount = "I0108126"
url = "http://intapi.sgap.253.com/send/sms"


#支付
[recharge]
payurl = "http://192.168.0.38:16080/api/pay/submit"
withdrawurl = "http://192.168.0.38:16080/api/withdraw/submit"


[jtpay]
usercode      = "11111111"
yingyongnum   = "11111111"
compkey       = "66666666666666666666666666666666"
notifyurl     = "https://xxx.com/happy/jtpay/notify"
returnurl     = "https://xxx.com/happy/jtpay/return"
placeorderurl = "https://order.z.jtpay.com/jh-web-order/order/receiveOrder"
ipwhitelist   = "127.0.0.1,127.0.0.1"
orderkey      = "G1xlgbN7zQn29RMGNvUvxqR4M7wFM+RWqlzlUrqhM7w"

[mlpay]
appid           = "1000100020003057"
applicationId   = "52"
md5             = "DDA50DB0B43745708601F3421CC4E85B"
withDrawMd5     = "F4F8B19FEC02479BACBAA63229494471"
payorderurl     = "https://api.lovetigervip.com/"
paynotifyurl    = "http://13.229.184.158:8002//api/pay/notify"
withDrawnotifyurl   = "127.0.0.1,127.0.0.1"

[xfpay]
machid          = "aa8a15a87a07455cb3bc6b9d9771c79d"
md5             = "b587a3624d0544adb081e1cceb8a3f9b"
withDrawMd5     = "41bf772edebb498a9c70c587e80334fe"
payorderurl     = "http://pay.desles.xyz"
paynotifyurl    = "http://13.229.184.158:8002/api/pay/notify"
withDrawnotifyurl   = "http://13.229.184.158:8002/api/withdraw/notify"

[kingpay]
appid           = "BH0CW9q0RgSslsac"
applicationId   = "1137"
serverPubRSA    = "MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAL3GnxmCrIIz9Jd0ISejOqCsmgxlDpQi8k9sKa4pHhphgS83YBRHA76VNCqEQjMgK1CQJGVcbKsqHd9mRZCPrSMCAwEAAQ=="
clientPubRSA    = "MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAMc8H3hgSEiSCoSbWOYsUzd34cqdFzE3HJza7lr3Zofo2IrdLsN4r0lpMsLTCgHF6NxC3akUzSvkWMnRtsaU+Y0CAwEAAQ=="
clientPriRSA    = "MIIBVwIBADANBgkqhkiG9w0BAQEFAASCAUEwggE9AgEAAkEAxzwfeGBISJIKhJtY5ixTN3fhyp0XMTccnNruWvdmh+jYit0uw3ivSWkywtMKAcXo3ELdqRTNK+RYydG2xpT5jQIDAQABAkEAhHtTRd1oU3FhMxqFu9C/qUO7Tdq1wFEwYpEmLDEU6cvaEPKUY+CRGRO4KoZCrFEaJcSGbm0+z84Rk11pJrfNFQIhAP81lRAJ30w01H9RCiwmO2BPQChCMfTCwrF3Aux9lkgbAiEAx9olFUs+Pvv/Y+LdNt/rPCAzgYgFAmgInV6lDjQ9r3cCIQDnd4Gq+kk8pO3WS3oecM6Jm1dlLCSDCeHrczWDqKQU4QIhAJjeglMhdQGUnKv5EqEw8qzRLNS+CKbokP5fMP4Gc9DNAiEAqGvZwrRfVdqkGNMUg8tHvJAYbooBj34SrGzEnggW9iw="
payorderurl     = "https://api.kingspay.top"
paynotifyurl    = "http://13.229.184.158:8002/api/pay/notify"
withDrawnotifyurl   = "http://13.229.184.158:8002/api/withdraw/notify"

[sailspay]
machid          = "102"
md5             = "nm4upo2hyhjqxzir"
payorderurl     = "https://api.sailspay.net/api"
paynotifyurl    = "http://171.221.148.255:16080/api/pay/notify/sailspay"
withDrawnotifyurl   = "http://171.221.148.255:16080/api/withdraw/notify/sailspay"

[domain]
name = "http://xxx.com"
headimag = "http://xxx.com/headimag"
admin = "http://xxx.com/admin"
sms = "http://xxx.com/happy/sms"
jtpay = "http://xxx.com/happy/jtpay"
web = "http://xxx.com/happy/web"
gate = "http://xxx.com/happy/gate"
download  = "https://xxx.com/happy/download"
