; Package name
NAME    = goserver
; Package version
VERSION = v1

[smsbao]
status = OFF
username = "11111111111"
password = "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"

[sms253]
status = OFF
account = "CN1111111"
password = "xxxxxxxxxxxxxx"
url = "http://smssh1.253.com/msg/send/json"

[smsbk]
status = OFF
appid = "U68zCsVP"
account = "PVxIvla0"
password = "24qPE8ci"
url = "https://api.onbuka.com/v3/sendSms"

[smskmi]
status = ON
accessKey = "e9fce16d048b4225bdd676b649309f59"
secretKey = "e391cecb906941da983ab2595be59394"
url = "http://api.kmicloud.com/sms/send/v1/otp"
template = "Please enter %s as your otp, never share to others. Pinaks"
sender = "PINAKO"

[smsxxy]
status = ON
appkey = "acQ3fF"
appsecret = "PaaQr1"
appcode = "1000"
url = "http://190.92.241.159:9090/sms/batch/v2"
template = "%s is the one time password to verify phone and activate your account with Hungryji"

[smsmt]
status = ON
appkey = "1X7wAD"
appsecret = "jh2CDi"
appcode = "1000"
url = "http://43.133.60.95:9090/sms/batch/v2"
template = "%s is the one time password to verify phone and activate your account with Hungryji"

[smscl]
status = ON
apiaccount = "I0108126"
password = "8DQM062Q71082d"
url = "http://intapi.253.com/send/json"

[smsmjlkmi]
status = ON
accessKey = "e5e6e0f81d72452fa6123332851ea853"
secretKey = "2f31b10cfc89464181e12da5ff2851e8"
url = "http://api.kmicloud.com/sms/send/v1/otp"
template = "Please enter %s as your otp, never share to others. Pinaks"
sender = "PINAKO"