player = 用户管理
logger = 日志管理
statistics = 统计管理
statistics2 = 统计管理（新）
pay = 财务管理
game = 游戏管理
message = 消息管理
user = 系统用户管理
role = 角色管理
upload = 上传管理
activity = 活动管理
channel = 渠道管理
main = 主页
gamestats=游戏统计
action = 操作管理
# 所有操作都需要以opt结尾
[main]
setpagesize = 分页设置

[user]
# add = 添加用户
# del = 删除用户
# edit = 编辑用户
list = 系统用户列表
listopt =系统用户列表(操作)

[role]
# add = 添加角色
# del = 删除角色
# edit = 编辑角色
list = 角色列表
listopt = 角色列表(操作)
# perm = 权限设置
[action]
list = 管理员操作日志

[player]
list = 用户列表
useropt = 用户列表(操作)
# edit = 资料修改
# editcoin = 修改奖励金
# editdiamond = 修改彩金
# rechargecoin = 充值奖励金
# rechargediamond = 充值彩金
# blacklistadd = 移入黑名单
# blacklistdel = 移出黑名单
onlineplayer = 在线玩家
blacklist = 黑白名单
blacklistopt = 黑白名单(操作)
goldlist = 金币流水
playlist = 对局列表
gamedetailsopt = 对局列表(操作)
equipmentadd = 设备码黑名单添加
gamecurve = 对局曲线

# shoplist = 充值配置
# shopadd = 添加配置
# shopedit = 修改配置
# shopdel = 移除商品
# gamelist = 游戏房间列表
# gameadd = 添加游戏房间
# gamedel = 移除游戏房间
# gameedit = 编辑游戏房间

[logger]
loginlist = 登录日志
# givediamond = 赠送金额日志
outdiamond = 可提现金额日志


[pay]
paylist = 充值记录
paylistopt = 充值记录(操作)
paylistexport = 充值记录(导出)
withdrawlist = 提现记录与审核
withdrawopt = 提现记录与审核(操作)
withdrawopttransferorder = 提现记录与审核(转单操作)
withdrawedit = 机审提现配置
# withdrawaudit = 提现审核通过
# withdrawfrozen = 提现冻结
# withdrawreturn = 提现退回
# withdrawtag = 提现标记
withdrawban = "提现封号"
withdrawlistexport = 提现记录与审核(导出)
withdrawswitchedit = 提现记录与审核(自动转单/派单开关设置)
channel = 渠道成功率
paychannelstats = 支付渠道统计
paychannelstatsopt = 支付渠道统计(操作)
paychannellog = 支付渠道日志
coinlog = 修改金币日志
# shoplist = 充值配置
# shopopt = 充值配置(操作)
# setwithdraw = 提现配置
# setwithdrawopt = 提现配置(操作)
# payblacklist = 支付黑名单
# payblacklistopt = 支付黑名单(操作)
# withdrawstats = 提现汇总统计
paychannelstatsexport=支付渠道统计(收付汇总导出)
paychannelstatnotice = 支付渠道统计通知
paychannel = 通道配置
paychanneledit = 通道配置(编辑)
paychannelopt = 通道配置(操作)
paychanneltest = 通道配置(测试)

[statistics]
livedata = 实时数据
livedataexport = 实时数据导出
datalist = 数据汇总
dtlist = 数据汇总(按时间)
# useranalysis = 大R分析
# useranalysisopt = 大R分析(操作)
useranalysis2 = 玩家分析
useranalysis2opt = 玩家分析(操作)
userlevelctype = 用户分层
; playeranalysis = 玩家分析总表
; playeranalysisopt = 玩家分析总表(操作)
goldflowcurve = 金币流水曲线
retained = 用户留存
ltvstat = LTV统计
ltvstatopt = LTV统计(操作)
gameltvstat = 游戏营收LTV
gameltvstatexport = 游戏营收LTV(导出)
firstpayltvstat = 首充口径LTV
recoverycycle = 回收周期计算
recoverycycleopt = 回收周期计算(操作)
losingplayers = 流失玩家分析页
playerrecharge = 玩家充值统计
goodsbuy = 商品购买统计
user = 用户资源
room = 房间数据
pointlist = 新用户埋点统计
pointlistopt = 新用户埋点统计(操作)
novicestock = 新手库存
novicestockopt = 新手库存(操作)
firstcharge = 首充分析
gamecharts = 游戏图表数据
buglist = Bug统计
checkstand = 收银台统计
adreport = AD上报统计
paysource = 充值来源
sms = 短信统计
roomresources = 正常库存
usergeneralstats = 玩家综合情况总览
usergeneralstatsexport = 玩家综合情况总览(导出)
playerbetstats = 打码统计
playerbetstatsexport = 打码统计(导出)

[statistics2]
ltvstat2 = LTV统计
behavioranalysis = 玩家行为分析
subprojectincome = 子项目收益
subprojectincomeopt = 子项目收益(操作)
gamestate = 游戏状态
rankinglist = 排行榜
playerdata = 玩家数据
tpstorystock = 剧情局盘口
daydatalist = 日数据汇总
daydatalistexport = 日数据汇总(导出)
financestats = 经济日报
financestatsexport = 经济日报(导出)
gamebetstats = 游戏行为日报
gamebetstatsexport = 游戏行为日报(导出)

[gamestats]
tp=TP统计
tpnew=TP统计(新)
lhd = LHD统计
updown = 7Updown统计
crash = Crash统计
ab = AndarBahar统计
cp = CP统计
plane = 飞机统计
rb = 红黑统计
mines = MINES统计

[message]
customer = 客服消息
customeropt = 客服消息(操作)
customermanager = 客服管理
customermanageropt = 客服管理(操作)
# customeradd = 新增聊天
# customerreply = 沟通
noticelist = 运营功能
noticelistopt = 运营功能(操作)
editshare = 社媒活动修改
# noticeadd = 添加跑马灯
# noticeedit = 修改跑马灯
# noticedel = 移除跑马灯


[game]
inventory = 库存列表
inventoryopt = 库存列表(操作)
stockinfo = 库存曲线
control = 点控玩家
controlopt = 点控玩家(操作)
# controledit = 点控设置
# gamelist = 房间列表
systemlist = 系统设置
systemlistopt = 系统设置(操作)
# systemedit = 修改系统设置
systemservice = 系统设置(客服权限)

[upload]
config = 配置上传

[activity]
basicpay = 基础付费活动
basicfree = 基础免费活动
sharing = 分享活动
sharingopt = 分享活动(操作)
miui = 小米活动
lottery = 彩票活动
Sharedraw = 玩游戏分享抽大奖活动
betrank = 排行榜
betrankexport = 排行榜导出
turn = 转盘
turnexport = 转盘导出
turnaudit = 转盘奖励审核
turntag = 转盘奖励标记
giftpackcode = 礼包码
giftpackcodeedit = 礼包码编辑
giftpackcodeexport = 礼包码导出
volatilitysubsidy = 波动返水
volatilitysubsidyexport = 波动返水导出
shareagent = 代理活动
shareagentexport = 代理活动导出
usercoupon = 满减券活动
usercouponopt = 满减券活动(操作)
usercouponexport = 满减券活动(导出)

[channel]
list = 渠道数据
listopt = 渠道数据(操作)
bloggeraccount = 博主账号
bloggeropt = 博主账号(操作)
