statistics = 统计管理
role = 角色管理
user = 系统用户管理
channel = 渠道管理
# 所有操作都需要以opt结尾

[statistics]
datalist = 数据汇总
share = 分享数据

[role]
# add = 添加角色
# del = 删除角色
# edit = 编辑角色
list = 角色列表
listopt = 角色列表(操作)
# perm = 权限设置

[user]
# add = 添加用户
# del = 删除用户
# edit = 编辑用户
list = 系统用户列表
listopt =系统用户列表(操作)

[channel]
bloggeraccount = 博主账号
bloggeropt = 博主账号(操作)