package main

import (
	"fmt"
	"goserver/misc/tool/pb"
	"io/ioutil"
	"sort"
	"strings"
)

var (
	packetPath  = "../../gen/pb/packet.go"  //打包协议文件路径
	unpackPath  = "../../gen/pb/unpack.go"  //解包协议文件路径
	rPacketPath = "../../gen/pb/rpacket.go" //机器人打包协议
	rUnpackPath = "../../gen/pb/runpack.go" //机器人解包协议
)

func bodyPacket2(ps []proto) string {
	var str string
	for _, v := range ps {
		str += fmt.Sprintf("case *%s:\n\t\tb, err := msg.(*%s).Marshal()\n\t\t%s\n\t", v.name, v.name, resultPacket(v.code))
		//str += fmt.Sprintf("case *%s:\n\t\t%s\n\t\tb, err := msg.(*%s).Marshal()\n\t\t%s\n\t", v.name, bodyPacketCode(v.code, v.name), v.name, resultPacket2(v.code))
	}
	return str
}

func bodyUnpack2(ps []proto) string {
	var str string
	for _, v := range ps {
		str += fmt.Sprintf("case %d:\n\t\tmsg := new(%s)\n\t\t%s\n\t", v.code, v.name, resultUnpack())
		//str += fmt.Sprintf("case %d:\n\t\tmsg := new(%s)\n\t\t%s\n\t\t%s\n\t", v.code, v.name, bodyUnpackCode(v.name), resultUnpack())
	}
	return str
}

func bodyClientPacket2(ps []proto) string {
	var str string
	for _, v := range ps {
		str += fmt.Sprintf("case *%s:\n\t\tb, err := msg.(*%s).Marshal()\n\t\t%s\n\t", v.name, v.name, resultPacket(v.code))
		//str += fmt.Sprintf("case *%s:\n\t\t%s\n\t\tb, err := msg.(*%s).Marshal()\n\t\t%s\n\t", v.name, bodyClientPacketCode(v.code, v.name), v.name, resultPacket(v.code))
	}
	return str
}

func bodyClientUnpack2(ps []proto) string {
	var str string
	for _, v := range ps {
		str += fmt.Sprintf("case %d:\n\t\tmsg := new(%s)\n\t\t%s\n\t", v.code, v.name, resultUnpack())
		//str += fmt.Sprintf("case %d:\n\t\tmsg := new(%s)\n\t\t%s\n\t\t%s\n\t", v.code, v.name, bodyClientUnpackCode(v.code), resultUnpack())
	}
	return str
}

func resultPacket(code int) string {
	return fmt.Sprintf("return %d, b, err", code)
}

func resultUnpack() string {
	return fmt.Sprintf(`err := msg.Unmarshal(b)
		return msg, err`)
}

type proto struct {
	name string
	code int
}

var protosPacket = []proto{}
var protosUnpack = []proto{}

func headPacket() string {
	return fmt.Sprintf(`// Code generated by tool/gen.go.
// DO NOT EDIT!

package pb

import (
	"errors"
)

//Packet 打包消息
func Packet(msg interface{}) (uint32, []byte, error) {
	switch msg.(type) {
	`)
}

func endPacket() string {
	return fmt.Sprintf(`default:
		return 0, []byte{}, errors.New("unknown message")
	}
}`)
}

func headUnpack() string {
	return fmt.Sprintf(`// Code generated by tool/gen.go.
// DO NOT EDIT!

package pb

import (
	"errors"
)

//Unpack 解包消息
func Unpack(id uint32, b []byte) (interface{}, error) {
	switch id {
	`)
}

func endUnpack() string {
	return fmt.Sprintf(`default:
		return nil, errors.New("unknown message")
	}
}`)
}

func headRpacket() string {
	return fmt.Sprintf(`// Code generated by tool/gen.go.
// DO NOT EDIT!

package pb

import (
	"errors"
)

//Rpacket 打包消息
func Rpacket(msg interface{}) (uint32, []byte, error) {
	switch msg.(type) {
	`)
}

func endRpacket() string {
	return endPacket()
}

func headRunpack() string {
	return fmt.Sprintf(`// Code generated by tool/gen.go.
// DO NOT EDIT!

package pb

import (
	"errors"
)

//Runpack 解包消息
func Runpack(id uint32, b []byte) (interface{}, error) {
	switch id {
	`)
}

func endRunpack() string {
	return endUnpack()
}

func genPacket(body string) {
	var str string
	str += headPacket()
	//str += bodyPacket()
	str += body
	str += endPacket()
	err := ioutil.WriteFile(packetPath, []byte(str), 0644)
	if err != nil {
		panic(fmt.Sprintf("write file err -> %v\n", err))
	}
}

func genUnpack(body string) {
	var str string
	str += headUnpack()
	//str += bodyUnpack()
	str += body
	str += endUnpack()
	err := ioutil.WriteFile(unpackPath, []byte(str), 0644)
	if err != nil {
		panic(fmt.Sprintf("write file err -> %v\n", err))
	}
}

func genClientPacket(body string) {
	var str string
	str += headRpacket()
	//str += bodyClientPacket()
	str += body
	str += endRpacket()
	err := ioutil.WriteFile(rPacketPath, []byte(str), 0644)
	if err != nil {
		panic(fmt.Sprintf("write file err -> %v\n", err))
	}
}

func genClientUnpack(body string) {
	var str string
	str += headRunpack()
	//str += bodyClientUnpack()
	str += body
	str += endRunpack()
	err := ioutil.WriteFile(rUnpackPath, []byte(str), 0644)
	if err != nil {
		panic(fmt.Sprintf("write file err -> %v\n", err))
	}
}

func main() {
	keys := make([]int, 0, len(pb.Commands_name))
	for k := range pb.Commands_name {
		keys = append(keys, int(k))
	}
	sort.Ints(keys)

	for _, key := range keys {
		value := pb.Commands_name[int32(key)]

		if strings.HasSuffix(value, "Req") {
			protosUnpack = append(protosUnpack, proto{name: value, code: key})
		} else if strings.HasSuffix(value, "Rsp") {
			protosPacket = append(protosPacket, proto{name: value, code: key})
		} else if strings.HasSuffix(value, "Ntf") {
			protosPacket = append(protosPacket, proto{name: value, code: key})
		} else {
			fmt.Printf("unknow command %s:%d", value, key)
		}
	}

	var packetStr string
	var unpackStr string
	var rpacketStr string
	var runpackStr string

	packetStr += bodyPacket2(protosPacket)
	unpackStr += bodyUnpack2(protosUnpack)
	rpacketStr += bodyClientPacket2(protosUnpack)
	runpackStr += bodyClientUnpack2(protosPacket)

	//server
	genPacket(packetStr)
	genUnpack(unpackStr)
	//client
	genClientPacket(rpacketStr)
	genClientUnpack(runpackStr)

}
